### PR TITLE
Create Hello_World.kt

### PR DESCRIPTION
**Pull request by Ishika0-0**
added a hello world program in kotlin program
solved issue #101

### CODE REVIEW

**Comment by Ishika0-0** [comment]
@newridho 
kindly merge this issue under hacktoberfest2024

**Comment by newridho** [comment]
okay, but u need to rename the file. Look the [Contribution Guidelines](https://github.com/newridho/Halo-Dunia24/blob/main/CONTRIBUTING.md)

**Comment by Ishika0-0** [comment]
@newridho done renaming can you merge it now

**Review by Ishika0-0 — COMMENTED** [review]
Rename file name

**Comment by newridho** [comment]
thanks for the contribution dude🔥🔥

**Pull request merged**
